
meta_product_name: "Timply"
meta_title: " Timply - Envois de Courrier et Lettre suivie moins cher grâce aux timbres de collection."
meta_description: "La solution pour des achats d'enveloppes pré-timbrées, lettres vertes, lettres prioritaires, lettres recommandées, lettres suivies moins cher que la Poste"
meta_image: "pack.png" # should exist in `app/assets/images/`
  # required for Twitter Cards
